import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#83f6e2",
        tertiary: "#e85d5d",
        "inverse-on-surface": "#f3f0f0",
        "secondary-fixed-dim": "#f8bc63",
        outline: "#6d7a76",
        "inverse-primary": "#65d9c6",
        "on-tertiary-fixed": "#410006",
        "tertiary-fixed-dim": "#ffb3b0",
        "primary-container": "#008375",
        "surface-container": "#f0eded",
        "secondary-fixed": "#ffddb2",
        background: "#fcf9f8",
        "on-primary-fixed": "#00201c",
        "on-background": "#1b1c1c",
        "tertiary-container": "#ca4749",
        "surface-container-low": "#f6f3f2",
        "on-primary-container": "#f4fffb",
        "on-secondary-fixed-variant": "#624000",
        "inverse-surface": "#303030",
        "surface-bright": "#fcf9f8",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        primary: "#0f9d8c",
        "on-surface": "#2e2e2e",
        "on-secondary-fixed": "#291800",
        "outline-variant": "#bcc9c5",
        "surface-container-high": "#eae7e7",
        "secondary-container": "#fec168",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#3d4946",
        "surface-container-highest": "#e4e2e1",
        "surface-tint": "#006b5e",
        error: "#ba1a1a",
        secondary: "#f4b860",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-variant": "#e4e2e1",
        "on-tertiary-fixed-variant": "#8b1820",
        surface: "#fcf9f8",
        "primary-fixed-dim": "#65d9c6",
        "on-tertiary-container": "#fffbff",
        "on-primary-fixed-variant": "#005047",
        "surface-dim": "#dcd9d9",
        "tertiary-fixed": "#ffdad8",
        "on-secondary-container": "#774e00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "48px",
        base: "8px",
        "margin-desktop": "64px",
        md: "24px",
        xs: "4px",
        sm: "12px",
        "margin-mobile": "20px",
        gutter: "24px",
        xl: "80px",
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
